spring.application.name=inclusao-digital

spring.datasource.password=postgrespass
spring.datasource.username=postgresuser
spring.datasource.url=jdbc:postgresql://localhost:5432/inclusao_digital
spring.jpa.show-sql=true

authentication.jwt.issuer=inclusao-digital-application
authentication.algorithm.secret=5158ad4e-2123-4513-9bb1-b5e8532a5787

spring.websocket.enabled=true
